### ISSUE TITLE
Stereo Mix

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-audio#9]
How hard would it be to use my computers sounds instead of a microphones?

**Comment by zombodotcom** [comment]
Sound reactivity like this project uses an msgeq7. The way it's getting the signal can be either microphone or from an aux cable. https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F251977940811
Here's a link with one that uses aux / stereo

**Comment by jordanadania** [comment]
So the MSGEQ7 will have EITHER microphone OR AUX? Not both?

Is that the difference im seeing in the 2 identical items on ebay? One is microphone and one is Aux?

One is 16 and one is 20$

**Comment by jasoncoon** [comment]
One has a single MSGEQ7 chip and a mono audio input.  It'll provide 7 bands.

The other has two MSGEQ7 chips and a stereo audio input.  It'll provide 14 bands (7 left and 7 right).

Neither comes with a microphone.  You could connect a microphone to the input.

**Comment by jordanadania** [comment]
So I will need an aux splitter so I can hear the sounds the chip is visualizing, correct?

**Comment by jordanadania** [comment]
Also, does your code take advantage of 14 bands?

**Comment by zombodotcom** [comment]
The msgeq7 has 7 bands. 2 msgeq7's will still have a total of 7 eq bands because the chip was designed to only get those bands. On stereo Msgeq7 boards there are  two msgeq7's, one to grab the 7 bands from left and one to grab the 7 bands from right. The link I posted about the stereo Msgeq7 board on eBay is just one way to interface with the chip, some people use microphones if they designed their circuit to use that. 

Macetech has a great write-up on the Msgeq7 and microphones, http://macetech.com/blog/node/139 

But I just use the eBay one for strereo and a single band version that I designed on pcb with a mic for a portable version. 

Hope this helps. You can use either a mic or an aux it just depends on what the circuit that you're using is designed to do, is it stereo ( 2 msgeq7's) does it get input from a mic or aux? 

I'd just get the stereo Msgeq7 board from eBay and I'm pretty sure you'll be happy. Unless you want to build it yourself.

**Comment by jordanadania** [comment]
I bought the stereo to be safe. Idk what my plans are other than to learn.

**Comment by jordanadania** [comment]
Chip Arrived. But the readme is for the single chip. How do I wire up the stereo one for this project?

**Comment by zombodotcom** [comment]
you can use the stereo as a single as well. you could get a stereo to mono cable to convert it to where 1 side just gets all the data, vs  left and right.  You can also just plug in only the left or right pin from the board to arduino. you don't technically need both, but it is helpful. I suggest checking out the aura radiate and and some of the patterns that drew andre and a few other people made here that i added to my projects. 

https://github.com/zombodotcom/AuraRadiate2/blob/8c5147359f551e4c0850066ecdb43d93947cf0cd/Auraradiate2.ino#L777

https://github.com/zombodotcom/AuraRadiate2/blob/8c5147359f551e4c0850066ecdb43d93947cf0cd/Auraradiate2.ino#L777

**Comment by jordanadania** [comment]
If I did the stereo to mono adapter, how would that work with a stereo port? Which side would receive all the data?
